version: "3.9"  

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/app
    env_file:  
      - .env
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:  
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:  
      - .db.env 


volumes:  
  postgres_data:  
    driver: local